services:
  stmapp:
    container_name: stm-client
    image: docker-registry.hikarizsu.fr/OSM-frontend:latest
    env_file: ''
    ports:
      - "8144:80"
    volumes:
      - /etc/letsencrypt/live/hikarizsu.fr:/etc/letsencrypt/live/hikarizsu.fr:ro
      - /etc/letsencrypt/archive/hikarizsu.fr:/etc/letsencrypt/archive/hikarizsu.fr:ro
    working_dir: /app
    mem_limit: 350M
    memswap_limit: 4G
