#global
app_directory: /prodservices/docker/webserver/stmproject/
registry_url: docker-registry.home.hikarizsu.fr
registry_login: github_secrets
registry_pwd: github_secrets

# required for client
client_server_name: stm-test.hikarizsu.fr

# system vars
api_server_port: 8147
client_container_port: 80
mem_limit: 350M
memswap_limit: 4G
api_env_path: ./api.env
client_env_path: ./client.env


#### Customisable vars
# requred general
deploy_mode: test
deploy_mode: test
image_tag: test