name: Projet CI Docker Push Docker image
on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main']
#test
jobs:
  build-backend:
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
          
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            docker-registry.hikarizsu.fr/osm-backend:latest
            docker-registry.hikarizsu.fr/osm-backend:${{ github.sha }}

  build-frontend:
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./client/stmapp
          file: ./client/stmapp/Dockerfile
          push: true
          tags: |
            docker-registry.hikarizsu.fr/osm-frontend:latest
            docker-registry.hikarizsu.fr/osm-frontend:${{ github.sha }}

  deploye-test-server:  
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/develop' || github.base_ref == 'develop'
    uses: ./.github/workflows/ansible-deploy.yml
    with:
      deploy_mode: test
      api_server_name: stm-api-test.hikarizsu.fr
      client_server_name: stm-client-test.hikarizsu.fr 
      api_server_port: "8147"
      client_server_port: "8148"
      project_directory: /prodservices/docker/webserver/stmproject #do not set / at the end
      api_env_content: ${{ secrets.API_ENV_DEV }}
      client_env_content: " "
    secrets:
      HS_SSHKEY: ${{ secrets.HS_SSHKEY }}
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
      ADDRESS: ${{ secrets.ADDRESS }}