name: Projet CI Docker Push Docker image
on:
  push:
    branches: ['main', 'develop']
  # pull_request:
  #   branches: ['main']

jobs:
  build-backend:
    if: github.ref == 'refs/heads/main'
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  
          submodules: recursive 
          ref: ${{ github.ref }}
      
      - name: Reset to branch
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
          
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          build-args: |
            CONFIG=production
          tags: |
            docker-registry.hikarizsu.fr/osm-backend:latest
            docker-registry.hikarizsu.fr/osm-backend:latest-${{ github.sha }}

  build-frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  
          submodules: recursive 
          
      - name: Reset to branch
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./client/stmapp
          file: ./client/stmapp/Dockerfile
          push: true
          build-args: |
            CONFIG=production
          tags: |
            docker-registry.hikarizsu.fr/osm-frontend:latest
            docker-registry.hikarizsu.fr/osm-frontend:latest-${{ github.sha }}

  build-test-backend:
    if: github.ref == 'refs/heads/develop'
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  
          submodules: recursive

      - name: Reset to branch
        run: |
          git fetch origin develop
          git reset --hard origin/develop

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
          
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          build-args: |
            CONFIG=test
          tags: |
            docker-registry.hikarizsu.fr/osm-backend:test
            docker-registry.hikarizsu.fr/osm-backend:test-${{ github.sha }}

  build-test-frontend:
    if: github.ref == 'refs/heads/develop'
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  
          submodules: recursive 
          
      - name: Reset to branch
        run: |
          git fetch origin develop
          git reset --hard origin/develop

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./client/stmapp
          file: ./client/stmapp/Dockerfile
          push: true
          build-args: |
            CONFIG=test
          tags: |
            docker-registry.hikarizsu.fr/osm-frontend:test
            docker-registry.hikarizsu.fr/osm-frontend:test-${{ github.sha }}

  deploye-test-server:  
    needs: [build-test-backend, build-test-frontend]
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/ansible-deploy.yml
    with:
      deploy_mode: test
      image_tag: test-${{github.sha}}
      api_server_name: stm-api-test.hikarizsu.fr
      client_server_name: stm-client-test.hikarizsu.fr 
      api_server_port: "8147"
      client_server_port: "8148"
      project_directory: /prodservices/docker/webserver/stmproject #do not set / at the end
    secrets:
      HS_SSHKEY: ${{ secrets.HS_SSHKEY }}
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
      ADDRESS: ${{ secrets.ADDRESS }}

  deploye-prod-server:  
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-deploy.yml
    with:
      deploy_mode: prod
      image_tag: latest-${{github.sha}}
      api_server_name: stm-api.hikarizsu.fr
      client_server_name: stm-client.hikarizsu.fr
      api_server_port: "8143"
      client_server_port: "8144"
      project_directory: /prodservices/docker/webserver/stmproject #do not set / at the end
    secrets:
      HS_SSHKEY: ${{ secrets.HS_SSHKEY }}
      LOGIN: ${{ secrets.LOGIN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      ANSIBLE_INVENTORY: ${{ secrets.ANSIBLE_INVENTORY }}
      ADDRESS: ${{ secrets.ADDRESS }}