name: Projet CI Docker Push Docker image
on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main']
#test
jobs:
  build-backend:
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
          
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            docker-registry.hikarizsu.fr/osm-backend:latest
            docker-registry.hikarizsu.fr/osm-backend:${{ github.sha }}


  build-frontend:
    runs-on: [Linux, self-hosted, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: https://docker-registry.hikarizsu.fr
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      
      - name: set up buildx (builder)
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to registry
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            docker-registry.hikarizsu.fr/osm-frontend:latest
            docker-registry.hikarizsu.fr/osm-frontend:${{ github.sha }}



